# Define the name of the workflow
name: Hello World

# Define the event that triggers the workflow
on:
  push:  # This workflow will be triggered on any push event

# Define the jobs that the workflow will run
jobs:
  my-job:
    # Define the type of environment the job will run on
    runs-on: ubuntu-latest
    
    # Define the steps that the job will execute
    steps:
      - name: Print Hello World  # Define the name of the step
        run: "git hub actions testing"  # The command that the step will execute
